//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.JobApplicationReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobApplication", Namespace="http://schemas.datacontract.org/2004/07/WcfJobPortal")]
    [System.SerializableAttribute()]
    public partial class JobApplication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobApplicantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobApplicantId {
            get {
                return this.JobApplicantIdField;
            }
            set {
                if ((this.JobApplicantIdField.Equals(value) != true)) {
                    this.JobApplicantIdField = value;
                    this.RaisePropertyChanged("JobApplicantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobApplicationId {
            get {
                return this.JobApplicationIdField;
            }
            set {
                if ((this.JobApplicationIdField.Equals(value) != true)) {
                    this.JobApplicationIdField = value;
                    this.RaisePropertyChanged("JobApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobId {
            get {
                return this.JobIdField;
            }
            set {
                if ((this.JobIdField.Equals(value) != true)) {
                    this.JobIdField = value;
                    this.RaisePropertyChanged("JobId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobApplicationReference.IJobApplicationService")]
    public interface IJobApplicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplicationService/GetJobApplicationsOfApplicant", ReplyAction="http://tempuri.org/IJobApplicationService/GetJobApplicationsOfApplicantResponse")]
        System.Data.DataSet GetJobApplicationsOfApplicant(int jobApplicantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplicationService/GetJobApplicationsOfApplicant", ReplyAction="http://tempuri.org/IJobApplicationService/GetJobApplicationsOfApplicantResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetJobApplicationsOfApplicantAsync(int jobApplicantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplicationService/GetJobApplicationsOfJobCategory", ReplyAction="http://tempuri.org/IJobApplicationService/GetJobApplicationsOfJobCategoryResponse" +
            "")]
        System.Data.DataSet GetJobApplicationsOfJobCategory(int jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplicationService/GetJobApplicationsOfJobCategory", ReplyAction="http://tempuri.org/IJobApplicationService/GetJobApplicationsOfJobCategoryResponse" +
            "")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetJobApplicationsOfJobCategoryAsync(int jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplicationService/ApplyJob", ReplyAction="http://tempuri.org/IJobApplicationService/ApplyJobResponse")]
        int ApplyJob(WebApplication5.JobApplicationReference.JobApplication ja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplicationService/ApplyJob", ReplyAction="http://tempuri.org/IJobApplicationService/ApplyJobResponse")]
        System.Threading.Tasks.Task<int> ApplyJobAsync(WebApplication5.JobApplicationReference.JobApplication ja);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobApplicationServiceChannel : WebApplication5.JobApplicationReference.IJobApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobApplicationServiceClient : System.ServiceModel.ClientBase<WebApplication5.JobApplicationReference.IJobApplicationService>, WebApplication5.JobApplicationReference.IJobApplicationService {
        
        public JobApplicationServiceClient() {
        }
        
        public JobApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetJobApplicationsOfApplicant(int jobApplicantId) {
            return base.Channel.GetJobApplicationsOfApplicant(jobApplicantId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetJobApplicationsOfApplicantAsync(int jobApplicantId) {
            return base.Channel.GetJobApplicationsOfApplicantAsync(jobApplicantId);
        }
        
        public System.Data.DataSet GetJobApplicationsOfJobCategory(int jobId) {
            return base.Channel.GetJobApplicationsOfJobCategory(jobId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetJobApplicationsOfJobCategoryAsync(int jobId) {
            return base.Channel.GetJobApplicationsOfJobCategoryAsync(jobId);
        }
        
        public int ApplyJob(WebApplication5.JobApplicationReference.JobApplication ja) {
            return base.Channel.ApplyJob(ja);
        }
        
        public System.Threading.Tasks.Task<int> ApplyJobAsync(WebApplication5.JobApplicationReference.JobApplication ja) {
            return base.Channel.ApplyJobAsync(ja);
        }
    }
}
